services:
  app:
    image: enterprise-todoapp
    command: -- --host # passed to vite dev
    environment:
      - DATABASE_URL=mysql://root:supersecurepass@0.0.0.0:3306/tododb
    ports:
      - '8000:5173'
